# Generated by Django 5.0.6 on 2024-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_persona_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='año',
            field=models.IntegerField(),
        ),
    ]
