# Generated by Django 5.0.6 on 2024-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogadmin_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.DeleteModel(
            name='blogAdmin',
        ),
    ]
